### ISSUE TITLE
Fight Words Airtable (Updated 5/19 @ 9:20AM)

### ISSUE THREAD

**Issue by AidenSPS** [AidenSPS/Coders-Batman-RPG#15]
[Airtable](https://airtable.com/invite/l?inviteId=invtqtZo6eZad43Ea&inviteToken=6c2031354f67c3441154277ac2e9868c46e7935011df661b03a12ace766bc03a&utm_source=email): To the Fight Words. Do we want these after every turn or is this randomized. If so, do we want to gaurentee one per melee?

**Comment by bmoreinis** [comment]
Please have Esa convert this so that each fight word is it's own record (not one record with all the fight words).  Each record should have an autonumber ID, the word, and the image.  We can then use a random function to pick one.
